#!/bin/sh

CURWDIR="$(cd $(dirname $0) && pwd)"
TITLE="背光控制"
PROGRAM_NAME="backlight-control"
CUSTOM_BIN="/system/apps/tp/bin/custom"
CUSTOM_CONFIG_FILE="$CURWDIR/custom.conf"

APPS_CONFIG_DIR="/data/conf"
LAUNCHER_CONFIG_DIR="$APPS_CONFIG_DIR/launcher/conf.d"
LAUNCHER_CONFIG_FILE="$LAUNCHER_CONFIG_DIR/$PROGRAM_NAME.conf"

ICON="res/appicon_backlight_normal.png"
PRESSED_ICON="res/appicon_backlight_pressed.png"

PID_FILE="$CURWDIR/$PROGRAM_NAME.pid"
PKILL_BIN="/usr/bin/pkill"
INSTALL_BIN="/usr/bin/install"
REMOVE="/bin/rm -f"
LUA_BIN="/system/bin/lua"
LUA_SCRIPT_PATH="/system/share/lua/5.1/tp_entry.lua"

INTERVAL="$CURWDIR/interval.conf";

usage() {
    echo "ERROR: action missing"
    echo "syntax: $0 <start|stop|restart|status|config|install|uninstall>"
    echo "example: $0 start"
}

start() {
    echo "not implemented"
}

stop() {
    echo "not implemented"
}

get_current_backlight_strategy()
{
    # 检测之前的背光控制策略
    local blhold=`cat /var/run/blhode`
    local bltime=`nvram_get 2860 BLtime`
    local idx=-1
    local txt="未知"

    if [ "$blhold" == "1" -o "$bltime" == "0" ] ; then
        idx=3
        txt="从不"
    elif [ "$bltime" == "180" ] ; then
        idx=0
        txt="3分钟"
    elif [ "$bltime" == "600" ] ; then
        idx=1
        txt="10分钟"
    elif [ "$bltime" == "1800" ] ; then
        idx=2
        txt="30分钟"
    fi    

    current_strategy=$idx
    current_strategy_txt=$txt
}

sync_strategy_to_datajson()
{
    get_current_backlight_strategy

    json4sh.sh set $CURWDIR/conf/data.json "current_strategy" value $current_strategy_txt
}

set_strategy()
{
    # 修改了之背光控制的实现策略,之前通过lua调用，（等同于lock_backlight.sh，是通过开关控制blcontrol是否生效)，而其实可以通过给blcontrol传递时间间隔参数0来实现背光长亮，这样和自定义背光控制时间间隔的逻辑一致，更简单方便 --阿耀
    local seconds=$1
    local pid=`ps|grep blcontrol|grep -v grep|awk '{print $1}'`;

    release_backlight.sh

    nvram_set 2860 BLtime $seconds
    kill $pid
    /bin/blcontrol -t $seconds -s NULL &

    sync_strategy_to_datajson
}

run() {
    get_current_backlight_strategy
    
    # 启动背光控制的list
    $CURWDIR/list -t "背光控制" -s $current_strategy -w $CURWDIR -c $CURWDIR/conf/list.conf &
}

install() 
{
    echo "{" > "$PROGRAM_NAME.conf"
    echo "\"name\" :  \"$TITLE\"," >> "$PROGRAM_NAME.conf"
    echo "\"icon\" : \"$CURWDIR/$ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"iconPressed\" : \"$CURWDIR/$PRESSED_ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"exec\" : \"$CURWDIR/init run\"," >> "$PROGRAM_NAME.conf"
    echo "\"msgNum\" : 4" >> "$PROGRAM_NAME.conf"
    echo "}" >> "$PROGRAM_NAME.conf"

    $INSTALL_BIN -d $LAUNCHER_CONFIG_DIR
    $INSTALL_BIN "$PROGRAM_NAME.conf" "$LAUNCHER_CONFIG_FILE"    

    sync_strategy_to_datajson
}



uninstall() {
    $REMOVE "$LAUNCHER_CONFIG_FILE"
}

# main
if [ $# -lt 1 ]; then
    usage
    exit 255
fi

case "$1" in
    "start" )
        start;;
    "stop" )
        stop;;
    "run" )
        run;;
    "restart" )
        start
        stop;;
    "install" )
        install;;
    "uninstall" )
        uninstall;;
    "config" )
    	config;;
    "set_strategy" )
        set_strategy $2 ;;    
    * )
        usage ;;
esac
