#!/bin/sh

CURWDIR="$(cd $(dirname $0) && pwd)"
TITLE="背光控制"
PROGRAM_NAME="backlight-control"
CUSTOM_BIN="/system/apps/tp/bin/custom"
CUSTOM_CONFIG_FILE="$CURWDIR/custom.conf"

APPS_CONFIG_DIR="/data/conf"
LAUNCHER_CONFIG_DIR="$APPS_CONFIG_DIR/launcher/conf.d"
LAUNCHER_CONFIG_FILE="$LAUNCHER_CONFIG_DIR/$PROGRAM_NAME.conf"

ICON="appicon_backlight_normal.png"
PRESSED_ICON="appicon_backlight_pressed.png"

PID_FILE="$CURWDIR/$PROGRAM_NAME.pid"
PKILL_BIN="/usr/bin/pkill"
INSTALL_BIN="/usr/bin/install"
REMOVE="/bin/rm -f"
LUA_BIN="/system/bin/lua"
LUA_SCRIPT_PATH="/system/share/lua/5.1/tp_entry.lua"

usage() {
    echo "ERROR: action missing"
    echo "syntax: $0 <start|stop|restart|status|config|install|uninstall>"
    echo "example: $0 start"
}

start() {
    $CUSTOM_BIN "$CUSTOM_CONFIG_FILE" &
    [ "$!""XXX" != "XXX" ] && echo "$!" > $PID_FILE
}

stop() {
    if [ -f $PID_FILE ]; then
        $PKILL_BIN "$CUSTOM_BIN $CUSTOM_CONFIG_FILE" -F "$PID_FILE"
        $REMOVE $PID_FILE
    fi
}

config() {
    echo "{" > "$PROGRAM_NAME.conf"
    echo "\"name\" :  \"$TITLE\"," >> "$PROGRAM_NAME.conf"
    echo "\"icon\" : \"$CURWDIR/$ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"iconPressed\" : \"$CURWDIR/$PRESSED_ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"exec\" : \"$CURWDIR/init start\"," >> "$PROGRAM_NAME.conf"
    echo "\"msgNum\" : 4" >> "$PROGRAM_NAME.conf"
    echo "}" >> "$PROGRAM_NAME.conf"

    $INSTALL_BIN -d $LAUNCHER_CONFIG_DIR
    $INSTALL_BIN "$PROGRAM_NAME.conf" "$LAUNCHER_CONFIG_FILE"
}

uninstall() {
    $REMOVE "$LAUNCHER_CONFIG_FILE"
}

release_backlight() {
    RC=$($LUA_BIN $LUA_SCRIPT_PATH sys_api.release_backlight)
    echo -n $RC 
}

lock_backlight() {
    RC=$($LUA_BIN $LUA_SCRIPT_PATH sys_api.lock_backlight)
    echo -n $RC 
}

backlight_on() {
    RC=$($LUA_BIN $LUA_SCRIPT_PATH sys_api.wakeup_backlight)
    echo -n $RC
}

backlight_off() {
    echo -n '{"msg": "falilure", "code": -1}'
}

# main
if [ $# -lt 1 ]; then
    usage
    exit 255
fi

case "$1" in
    "start" )
        start;;
    "stop" )
        stop;;
    "restart" )
        start
        stop;;
    "install" )
        config;;
    "uninstall" )
        uninstall;;
    "config" )
        config;;
    "release_backlight" )
        release_backlight;;
    "lock_backlight" )
        lock_backlight;;
    "backlight_on" )
        backlight_on;;
    "backlight_off" )
        backlight_off;;
    * )
        usage ;;
esac
